language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install tox tox-travis
script:
  - tox -e integration
matrix:
  allow_failures:
  - python: "nightly"

dist: trusty
